### ISSUE TITLE
Make request personalizable

### ISSUE THREAD

**Issue by nicola** [solid/solid-signup#2]
At the moment I can do this:

```
https://solid.github.io/solid-signup/?domain=' + host
```

and this will make a request to my domain, however I can't personalize what url the requests head to, since `,system/*` are hard-coded, maybe can be passed as get param!

**Comment by deiu** [comment]
Fixed in 7a162428e965cc84cf583e20576cceb59f8739b7.

You can now use:

```
https://solid.github.io/solid-signup/?domain=' + host + '&acc=' + accountEndpoint + '&crt=' + certEndpoint
```
